### ISSUE TITLE
teaxyz/setup trying to double-install deno on ubuntu-latest

### ISSUE THREAD

**Issue by jhheider** [teaxyz/setup#142]
https://github.com/teaxyz/cli/actions/runs/4296236189/jobs/7487702098

```sh
Run teaxyz/setup@v0
  with:
    chaste: false
    srcroot: .
determining latest tea version…
fetching tea.xyz@0.[2](https://github.com/teaxyz/cli/actions/runs/4296236189/jobs/7487706156#step:5:2)4.7
inspecting pantries…
fetching pantries…
pantries init’d ⎷
deno.land=1.[3](https://github.com/teaxyz/cli/actions/runs/4296236189/jobs/7487706156#step:5:3)1.1 locking
deno.land=1.31.1 querying
deno.land=1.31.1 downloading
deno.land=1.31.1 downloading 36.0 MiB
deno.land=1.31.1 verifying
deno.land=1.31.1 extracting
installed: ~/.tea/deno.land/v1.31.1
deno.land=1.31.1 locking
deno.land=1.31.1 installed
deno.land=1.31.1 querying
deno.land=1.31.1 cache: hit
deno.land=1.31.1 verifying
deno.land=1.31.1 extracting

panic: spilt tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3Adest+already+exists.

----------------------------------------------------->> attachment begin
AlreadyExists: dest already exists.
    at https://deno.land/std@0.176.0/fs/move.ts:3:22
<<----------------------------------------------------- attachment end
Error: Command failed: /home/runner/.tea/tea.xyz/v0.2[4](https://github.com/teaxyz/cli/actions/runs/4296236189/jobs/7487706156#step:5:4).7/bin/tea --sync --env --keep-going  
inspecting pantries…
fetching pantries…
pantries init’d ⎷
deno.land=1.31.1 locking
deno.land=1.31.1 querying
deno.land=1.31.1 downloading
deno.land=1.31.1 downloading 36.0 MiB
deno.land=1.31.1 verifying
deno.land=1.31.1 extracting
installed: ~/.tea/deno.land/v1.31.1
deno.land=1.31.1 locking
deno.land=1.31.1 installed
deno.land=1.31.1 querying
deno.land=1.31.1 cache: hit
deno.land=1.31.1 verifying
deno.land=1.31.1 extracting

panic: spilt tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3Adest+already+exists.

----------------------------------------------------->> attachment begin
AlreadyExists: dest already exists.
    at https://deno.land/std@0.176.0/fs/move.ts:3:22
<<----------------------------------------------------- attachment end

    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:1[5](https://github.com/teaxyz/cli/actions/runs/4296236189/jobs/7487706156#step:5:6))
    at go (/home/runner/work/_actions/teaxyz/setup/v0/action.js:119:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:9[6](https://github.com/teaxyz/cli/actions/runs/4296236189/jobs/7487706156#step:5:7):5) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 69 6e [7](https://github.com/teaxyz/cli/actions/runs/4296236189/jobs/7487706156#step:5:8)3 70 65 63 74 69 6e 67 20 70 61 6e 74 72 69 65 73 e2 [8](https://github.com/teaxyz/cli/actions/runs/4296236189/jobs/7487706156#step:5:9)0 a6 0a 1b 5b 47 1b 5b 31 41 1b 5b 30 4a 66 65 74 63 68 6[9](https://github.com/teaxyz/cli/actions/runs/4296236189/jobs/7487706156#step:5:10) 6e 67 20 70 61 6e 74 72 69 65 ... [14](https://github.com/teaxyz/cli/actions/runs/4296236189/jobs/7487706156#step:5:15)25 more bytes>
  ],
  pid: [16](https://github.com/teaxyz/cli/actions/runs/4296236189/jobs/7487706156#step:5:17)03,
  stdout: <Buffer >,
  stderr: <Buffer 69 6e 73 70 65 63 74 69 6e 67 [20](https://github.com/teaxyz/cli/actions/runs/4296236189/jobs/7487706156#step:5:21) 70 61 6e 74 72 69 65 73 e2 80 a6 0a 1b 5b 47 1b 5b 31 41 1b 5b 30 4a 66 65 74 63 68 69 6e 67 20 70 61 6e 74 72 69 65 ... 14[25](https://github.com/teaxyz/cli/actions/runs/4296236189/jobs/7487706156#step:5:26) more bytes>
}
```

**Comment by mxcl** [comment]
This is presumably a tea/cli bug due to 0.24.7 that I didn't mean to release, but in there I changed locking from locking the whole tea prefix to just the package base.

However it’s beyond me how this could result, and secondly, I am confused as to why deno could end up with some kind of double installation situation anyway.
